server:
  port: 8082

spring:
  application:
    name: patient-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:patient-db}:${DB_PORT:5432}/${DB_NAME:patient_db}
    username: ${DB_USER:patient_user}
    password: ${DB_PASSWORD:patient_password}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info

auth:
  jwt:
    secret: ${AUTH_JWT_SECRET:change_me_to_a_real_secret_change_me}
